-- Starter migration; UUIDs are generated by application. Review and test first.
BEGIN;
CREATE TABLE source (id uuid PRIMARY KEY, name text NOT NULL, descriptor jsonb NOT NULL, enabled boolean NOT NULL DEFAULT false);
CREATE TABLE crawl_partition (id uuid PRIMARY KEY, source_id uuid NOT NULL REFERENCES source(id), partition_key text NOT NULL, cursor jsonb, revision bigint NOT NULL DEFAULT 0, lease_epoch bigint NOT NULL DEFAULT 0, lease_owner text, lease_until timestamptz, UNIQUE(source_id,partition_key));
CREATE TABLE document (id uuid PRIMARY KEY, source_id uuid NOT NULL REFERENCES source(id), external_id text NOT NULL, canonical_url text, discovered_at timestamptz NOT NULL DEFAULT now(), UNIQUE(source_id,external_id));
CREATE TABLE content_object (sha256 text PRIMARY KEY CHECK (sha256 ~ '^[0-9a-f]{64}$'), size_bytes bigint NOT NULL CHECK(size_bytes>=0), mime_type text NOT NULL);
CREATE TABLE artifact (id uuid PRIMARY KEY, sha256 text NOT NULL REFERENCES content_object(sha256), provider_id text NOT NULL, container text NOT NULL, object_key text NOT NULL, object_version text, transform_version text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(provider_id,container,object_key));
CREATE TABLE document_asset (document_id uuid NOT NULL REFERENCES document(id), artifact_id uuid NOT NULL REFERENCES artifact(id), role text NOT NULL, PRIMARY KEY(document_id,artifact_id,role));
CREATE TABLE job (id uuid PRIMARY KEY, document_id uuid REFERENCES document(id), operation text NOT NULL, idempotency_key text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','retry_wait','succeeded','failed','quarantined','cancelled')), input jsonb NOT NULL, attempt integer NOT NULL DEFAULT 0, max_attempts integer NOT NULL DEFAULT 5 CHECK(max_attempts>0), available_at timestamptz NOT NULL DEFAULT now(), lease_owner text, lease_epoch bigint NOT NULL DEFAULT 0, lease_until timestamptz, error_code text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX job_eligible ON job(available_at,id) WHERE status IN ('pending','retry_wait');
CREATE INDEX job_expired ON job(lease_until) WHERE status='running';
CREATE TABLE job_attempt (job_id uuid NOT NULL REFERENCES job(id), attempt integer NOT NULL, lease_epoch bigint NOT NULL, started_at timestamptz NOT NULL, ended_at timestamptz, error_redacted jsonb, PRIMARY KEY(job_id,attempt));
CREATE TABLE outbox_event (id uuid PRIMARY KEY, job_id uuid NOT NULL REFERENCES job(id), event_type text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz, dispatch_owner text, dispatch_until timestamptz, dispatch_epoch bigint NOT NULL DEFAULT 0);
CREATE INDEX outbox_pending ON outbox_event(created_at,id) WHERE published_at IS NULL;
CREATE TABLE dataset_release (id uuid PRIMARY KEY, purpose text NOT NULL, status text NOT NULL CHECK(status IN ('candidate','validated','released','withdrawn')), manifest jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
-- Production adds roles, dataset/run/rights/lineage tables and retention partitions.
-- Purpose-specific approval must be enforced by release service, not this starter JSON.
COMMIT;
