-- Draft extension AFTER 001. Integration/restore/permission tests not run.
BEGIN;
CREATE TABLE connection (id uuid PRIMARY KEY, connector_type text NOT NULL, account_ref text NOT NULL, secret_ref text NOT NULL, resource_scope jsonb NOT NULL, granted_operations jsonb NOT NULL, status text NOT NULL, adapter_version text NOT NULL, tested_at timestamptz);
CREATE TABLE acquisition_run (id uuid PRIMARY KEY, source_id uuid NOT NULL REFERENCES source(id), connection_id uuid REFERENCES connection(id), status text NOT NULL, purpose text NOT NULL, adapter_version text NOT NULL, budget jsonb NOT NULL, started_at timestamptz NOT NULL, ended_at timestamptz, counters jsonb NOT NULL DEFAULT '{}', cancel_generation bigint NOT NULL DEFAULT 0);
CREATE TABLE source_record (id uuid PRIMARY KEY, source_id uuid NOT NULL REFERENCES source(id), external_id text NOT NULL, record_type text NOT NULL, UNIQUE(source_id,external_id,record_type));
CREATE TABLE record_version (id uuid PRIMARY KEY, record_id uuid NOT NULL REFERENCES source_record(id), run_id uuid NOT NULL REFERENCES acquisition_run(id), version_key text NOT NULL, upstream_version text, observed_at timestamptz NOT NULL, source_modified_at timestamptz, deleted_at timestamptz, raw_artifact_id uuid REFERENCES artifact(id), schema_version integer NOT NULL, payload jsonb NOT NULL, unknown_reasons jsonb NOT NULL DEFAULT '{}', UNIQUE(record_id,version_key));
CREATE TABLE record_relation (from_record uuid NOT NULL REFERENCES source_record(id), to_record uuid NOT NULL REFERENCES source_record(id), relation_type text NOT NULL, PRIMARY KEY(from_record,to_record,relation_type));
CREATE TABLE record_observation (id uuid PRIMARY KEY, record_id uuid NOT NULL REFERENCES source_record(id), run_id uuid NOT NULL REFERENCES acquisition_run(id), observed_at timestamptz NOT NULL, metric_name text NOT NULL, metric_value numeric NOT NULL, UNIQUE(record_id,run_id,metric_name));
CREATE TABLE download_attempt (job_id uuid NOT NULL, attempt integer NOT NULL, stage text NOT NULL, http_status integer, error_category text, bytes_received bigint NOT NULL DEFAULT 0 CHECK(bytes_received>=0), entity_validator text, partial_ref jsonb, started_at timestamptz NOT NULL, ended_at timestamptz, PRIMARY KEY(job_id,attempt), FOREIGN KEY(job_id,attempt) REFERENCES job_attempt(job_id,attempt));
CREATE TABLE rights_review (id uuid PRIMARY KEY, record_version_id uuid NOT NULL REFERENCES record_version(id), purpose text NOT NULL, status text NOT NULL CHECK(status IN ('approved','pending','denied')), evidence_url text, reviewed_at timestamptz, unknown_reason text, CHECK(status<>'approved' OR (evidence_url IS NOT NULL AND reviewed_at IS NOT NULL)));
CREATE TABLE quality_check (id uuid PRIMARY KEY, record_version_id uuid NOT NULL REFERENCES record_version(id), check_name text NOT NULL, check_version text NOT NULL, result text NOT NULL CHECK(result IN ('pass','fail','unknown')), evidence jsonb NOT NULL, checked_at timestamptz NOT NULL);
CREATE TABLE artifact_lineage (parent_id uuid NOT NULL REFERENCES artifact(id), child_id uuid NOT NULL REFERENCES artifact(id), transform_version text NOT NULL, PRIMARY KEY(parent_id,child_id,transform_version), CHECK(parent_id<>child_id));
CREATE TABLE retention_policy (id uuid PRIMARY KEY, revision integer NOT NULL, mode text NOT NULL CHECK(mode IN ('keep','ttl','delete_after_release','archive_then_delete')), rules jsonb NOT NULL);
CREATE TABLE artifact_hold (id uuid PRIMARY KEY, artifact_id uuid NOT NULL REFERENCES artifact(id), reason text NOT NULL, expires_at timestamptz);
CREATE TABLE deletion_plan (id uuid PRIMARY KEY, policy_id uuid NOT NULL REFERENCES retention_policy(id), policy_revision integer NOT NULL, status text NOT NULL, dry_run boolean NOT NULL DEFAULT true, targets jsonb NOT NULL, dependency_generation bigint NOT NULL, expires_at timestamptz NOT NULL, result jsonb);
CREATE TABLE audit_event (id uuid PRIMARY KEY, principal_id text NOT NULL, operation text NOT NULL, resource_ref text NOT NULL, policy_revision text NOT NULL, outcome text NOT NULL, request_id text NOT NULL, occurred_at timestamptz NOT NULL, detail_redacted jsonb NOT NULL DEFAULT '{}');
CREATE TABLE usage_record (id uuid PRIMARY KEY, run_id uuid REFERENCES acquisition_run(id), job_id uuid REFERENCES job(id), provider text NOT NULL, model_revision text, input_tokens bigint, output_tokens bigint, bytes bigint, cost numeric, currency text, measured_at timestamptz NOT NULL);
COMMIT;
-- Missing production enforcement intentionally explicit: RLS/service roles,
-- append-only audit permissions, retention partitions, release-purpose joins,
-- lineage cycle validation, deletion fencing repository transactions.
-- source_record stores general records; document stays scholarly compatibility
-- projection. Add explicit mapping in repository, never duplicate identity authority.
